#!/bin/sh
#
# Start RNDIS....
#

start() {
    printf "Starting RNDIS: "
    modprobe g_ether
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping RNDIS: "
    modprobe -r g_ether
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
