#!/bin/sh
#
# Start btbcm....
#

start() {
    printf "Starting Bluetooth Driver: "
    modprobe hci_uart
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping Bluetooth Driver: "
    modprobe -r hci_uart
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
